# .github/workflows/bot.yml
name: PVP_HS Speedrun Bot
on:
  workflow_dispatch:

jobs:
  speedrun:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install packages
        run: |
          npm install mineflayer@4.23.0 \
                      mineflayer-pathfinder@2.4.5 \
                      minecraft-data@3.63.0 \
                      vec3@0.1.8

      - name: Run bot
        run: node bot.js
